/**
 * Production Database Schema Migration
 *
 * This migration recreates the exact production database structure from Neon.tech PostgreSQL.
 * Generated by inspecting the production database on 2025-01-09.
 *
 * Database: concetto on Neon.tech
 * This migration creates all tables, columns, constraints, indexes, and foreign keys
 * as they exist in the production environment.
 */

import { neon } from '@neondatabase/serverless';

// Types for database entities
export interface DatabaseSchema {
  tables: TableDefinition[];
  relationships: RelationshipDefinition[];
}

export interface TableDefinition {
  name: string;
  columns: ColumnDefinition[];
  constraints: ConstraintDefinition[];
  indexes: IndexDefinition[];
}

export interface ColumnDefinition {
  name: string;
  type: string;
  nullable: boolean;
  defaultValue?: string;
  maxLength?: number;
  precision?: number;
  scale?: number;
}

export interface ConstraintDefinition {
  name: string;
  type: 'PRIMARY KEY' | 'FOREIGN KEY' | 'UNIQUE' | 'CHECK';
  columns: string[];
  referenceTable?: string;
  referenceColumn?: string;
  onDelete?: string;
  onUpdate?: string;
  checkCondition?: string;
}

export interface IndexDefinition {
  name: string;
  columns: string[];
  unique: boolean;
  type?: string;
  where?: string;
}

export interface RelationshipDefinition {
  fromTable: string;
  fromColumn: string;
  toTable: string;
  toColumn: string;
  constraintName: string;
  onDelete: string;
  onUpdate: string;
}

/**
 * Production database schema definition
 */
const PRODUCTION_SCHEMA: DatabaseSchema = {
  tables: [
    // ============================================================
    // COMPANIES TABLE
    // ============================================================
    {
      name: 'companies',
      columns: [
        { name: 'id', type: 'uuid', nullable: false, defaultValue: 'gen_random_uuid()' },
        { name: 'code', type: 'text', nullable: false },
        { name: 'name', type: 'text', nullable: false },
        { name: 'address', type: 'text', nullable: true },
        { name: 'mobile', type: 'text', nullable: true },
        { name: 'email', type: 'text', nullable: true },
        { name: 'prepared_by', type: 'text', nullable: true },
        { name: 'terms', type: 'text', nullable: true },
        { name: 'del_note', type: 'text', nullable: true },
        { name: 'closing_note', type: 'text', nullable: true },
        { name: 'created_at', type: 'timestamp with time zone', nullable: false, defaultValue: 'now()' },
        { name: 'updated_at', type: 'timestamp with time zone', nullable: false, defaultValue: 'now()' },
        { name: 'cost_categories', type: 'jsonb', nullable: true, defaultValue: '\'["materials", "labor", "overhead", "shipping"]\'::jsonb' },
        { name: 'currency', type: 'text', nullable: true, defaultValue: '\'PHP\'::text' },
        { name: 'subscription_status', type: 'character varying(20)', nullable: true, defaultValue: '\'demo\'::character varying' },
        { name: 'trial_end', type: 'timestamp with time zone', nullable: true }
      ],
      constraints: [
        { name: 'companies_pkey', type: 'PRIMARY KEY', columns: ['id'] },
        { name: 'companies_code_key', type: 'UNIQUE', columns: ['code'] },
        { name: 'companies_subscription_status_check', type: 'CHECK', columns: ['subscription_status'], checkCondition: 'subscription_status IN (\'demo\', \'trialing\', \'active\', \'past_due\', \'cancelled\', \'unpaid\')' }
      ],
      indexes: [
        { name: 'companies_code_idx', columns: ['code'], unique: false, type: 'btree' },
        { name: 'companies_code_key', columns: ['code'], unique: true, type: 'btree' },
        { name: 'idx_companies_subscription_status', columns: ['subscription_status'], unique: false, type: 'btree' }
      ]
    },

    // ============================================================
    // USERS TABLE
    // ============================================================
    {
      name: 'users',
      columns: [
        { name: 'id', type: 'uuid', nullable: false, defaultValue: 'gen_random_uuid()' },
        { name: 'company_id', type: 'uuid', nullable: false },
        { name: 'email', type: 'text', nullable: true },
        { name: 'password_hash', type: 'text', nullable: true },
        { name: 'created_at', type: 'timestamp with time zone', nullable: false, defaultValue: 'now()' },
        { name: 'name_encrypted', type: 'bytea', nullable: true },
        { name: 'email_encrypted', type: 'bytea', nullable: true },
        { name: 'email_hash', type: 'text', nullable: true },
        { name: 'is_oauth_user', type: 'boolean', nullable: true, defaultValue: 'false' },
        { name: 'trial_expires_at', type: 'timestamp with time zone', nullable: true },
        { name: 'subscription_activated', type: 'boolean', nullable: true, defaultValue: 'false' },
        { name: 'activation_code', type: 'character varying(255)', nullable: true },
        { name: 'discount_percent', type: 'numeric', nullable: true },
        { name: 'subscription_plan', type: 'character varying(50)', nullable: true },
        { name: 'role', type: 'character varying(20)', nullable: true, defaultValue: '\'user\'::character varying' },
        { name: 'is_admin', type: 'boolean', nullable: true, defaultValue: 'false' }
      ],
      constraints: [
        { name: 'users_pkey', type: 'PRIMARY KEY', columns: ['id'] },
        { name: 'users_email_key', type: 'UNIQUE', columns: ['email'] },
        { name: 'users_company_id_required', type: 'CHECK', columns: ['company_id'], checkCondition: 'company_id IS NOT NULL' },
        { name: 'check_role', type: 'CHECK', columns: ['role'], checkCondition: 'role IN (\'user\', \'admin\', \'super_admin\')' }
      ],
      indexes: [
        { name: 'users_company_idx', columns: ['company_id'], unique: false, type: 'btree' },
        { name: 'users_email_key', columns: ['email'], unique: true, type: 'btree' },
        { name: 'users_email_idx', columns: ['email'], unique: false, type: 'btree' },
        { name: 'users_email_hash_idx', columns: ['email_hash'], unique: false, type: 'btree' },
        { name: 'idx_users_role', columns: ['role'], unique: false, type: 'btree' },
        { name: 'idx_users_is_admin', columns: ['is_admin'], unique: false, type: 'btree' },
        { name: 'idx_users_trial_expires', columns: ['trial_expires_at'], unique: false, type: 'btree' },
        { name: 'idx_users_subscription_status', columns: ['subscription_activated', 'trial_expires_at'], unique: false, type: 'btree' }
      ]
    },

    // ============================================================
    // OAUTH_ACCOUNTS TABLE
    // ============================================================
    {
      name: 'oauth_accounts',
      columns: [
        { name: 'id', type: 'uuid', nullable: false, defaultValue: 'gen_random_uuid()' },
        { name: 'user_id', type: 'uuid', nullable: false },
        { name: 'provider', type: 'text', nullable: false },
        { name: 'provider_user_id', type: 'text', nullable: false },
        { name: 'email', type: 'text', nullable: true },
        { name: 'username', type: 'text', nullable: true },
        { name: 'wallet_address', type: 'text', nullable: true },
        { name: 'access_token', type: 'text', nullable: true },
        { name: 'refresh_token', type: 'text', nullable: true },
        { name: 'expires_at', type: 'timestamp with time zone', nullable: true },
        { name: 'created_at', type: 'timestamp with time zone', nullable: true, defaultValue: 'now()' },
        { name: 'updated_at', type: 'timestamp with time zone', nullable: true, defaultValue: 'now()' }
      ],
      constraints: [
        { name: 'oauth_accounts_pkey', type: 'PRIMARY KEY', columns: ['id'] },
        { name: 'oauth_accounts_provider_provider_user_id_key', type: 'UNIQUE', columns: ['provider', 'provider_user_id'] },
        { name: 'oauth_accounts_provider_check', type: 'CHECK', columns: ['provider'], checkCondition: 'provider IN (\'google\', \'facebook\', \'github\')' }
      ],
      indexes: [
        { name: 'idx_oauth_accounts_user_id', columns: ['user_id'], unique: false, type: 'btree' },
        { name: 'idx_oauth_accounts_provider', columns: ['provider', 'provider_user_id'], unique: false, type: 'btree' },
        { name: 'idx_oauth_accounts_email', columns: ['email'], unique: false, type: 'btree', where: 'email IS NOT NULL' }
      ]
    },

    // ============================================================
    // PASSWORD_RESET_TOKENS TABLE
    // ============================================================
    {
      name: 'password_reset_tokens',
      columns: [
        { name: 'id', type: 'uuid', nullable: false, defaultValue: 'gen_random_uuid()' },
        { name: 'user_id', type: 'uuid', nullable: false },
        { name: 'token', type: 'text', nullable: false },
        { name: 'expires_at', type: 'timestamp with time zone', nullable: false },
        { name: 'used_at', type: 'timestamp with time zone', nullable: true },
        { name: 'created_at', type: 'timestamp with time zone', nullable: false, defaultValue: 'now()' }
      ],
      constraints: [
        { name: 'password_reset_tokens_pkey', type: 'PRIMARY KEY', columns: ['id'] }
      ],
      indexes: [
        { name: 'password_reset_tokens_user_idx', columns: ['user_id'], unique: false, type: 'btree' },
        { name: 'password_reset_tokens_token_idx', columns: ['token'], unique: false, type: 'btree' },
        { name: 'password_reset_tokens_expires_idx', columns: ['expires_at'], unique: false, type: 'btree' }
      ]
    },

    // ============================================================
    // PRODUCTS TABLE
    // ============================================================
    {
      name: 'products',
      columns: [
        { name: 'id', type: 'uuid', nullable: false, defaultValue: 'gen_random_uuid()' },
        { name: 'code', type: 'text', nullable: false },
        { name: 'collection', type: 'text', nullable: true },
        { name: 'description', type: 'text', nullable: false },
        { name: 'unit', type: 'text', nullable: false, defaultValue: '\'sqft\'::text' },
        { name: 'active', type: 'boolean', nullable: false, defaultValue: 'true' },
        { name: 'created_at', type: 'timestamp with time zone', nullable: false, defaultValue: 'now()' },
        { name: 'updated_at', type: 'timestamp with time zone', nullable: false, defaultValue: 'now()' }
      ],
      constraints: [
        { name: 'products_pkey', type: 'PRIMARY KEY', columns: ['id'] },
        { name: 'products_code_key', type: 'UNIQUE', columns: ['code'] },
        { name: 'products_unit_check', type: 'CHECK', columns: ['unit'], checkCondition: 'unit IN (\'sqft\', \'sqm\', \'linear_ft\', \'linear_m\', \'each\')' }
      ],
      indexes: [
        { name: 'products_code_key', columns: ['code'], unique: true, type: 'btree' },
        { name: 'products_code_idx', columns: ['code'], unique: false, type: 'btree' }
      ]
    },

    // ============================================================
    // COMPANY_PRODUCTS TABLE
    // ============================================================
    {
      name: 'company_products',
      columns: [
        { name: 'id', type: 'uuid', nullable: false, defaultValue: 'gen_random_uuid()' },
        { name: 'company_id', type: 'uuid', nullable: false },
        { name: 'product_id', type: 'uuid', nullable: false },
        { name: 'supplier_cost', type: 'numeric', nullable: false, defaultValue: '0' },
        { name: 'retail_price', type: 'numeric', nullable: false, defaultValue: '0' }
      ],
      constraints: [
        { name: 'company_products_pkey', type: 'PRIMARY KEY', columns: ['id'] },
        { name: 'company_products_company_id_product_id_key', type: 'UNIQUE', columns: ['company_id', 'product_id'] }
      ],
      indexes: [
        { name: 'company_products_company_idx', columns: ['company_id'], unique: false, type: 'btree' },
        { name: 'company_products_product_idx', columns: ['product_id'], unique: false, type: 'btree' }
      ]
    },

    // ============================================================
    // COMPANY_COLLECTIONS TABLE
    // ============================================================
    {
      name: 'company_collections',
      columns: [
        { name: 'id', type: 'uuid', nullable: false, defaultValue: 'gen_random_uuid()' },
        { name: 'company_id', type: 'uuid', nullable: false },
        { name: 'collection', type: 'text', nullable: false },
        { name: 'supplier_cost', type: 'numeric', nullable: false, defaultValue: '0' },
        { name: 'retail_price', type: 'numeric', nullable: false, defaultValue: '0' }
      ],
      constraints: [
        { name: 'company_collections_pkey', type: 'PRIMARY KEY', columns: ['id'] },
        { name: 'company_collections_company_id_collection_key', type: 'UNIQUE', columns: ['company_id', 'collection'] }
      ],
      indexes: [
        { name: 'company_collections_company_idx', columns: ['company_id'], unique: false, type: 'btree' },
        { name: 'company_collections_collection_idx', columns: ['collection'], unique: false, type: 'btree' }
      ]
    },

    // ============================================================
    // COMPANY_PRODUCT_DEFINITIONS TABLE
    // ============================================================
    {
      name: 'company_product_definitions',
      columns: [
        { name: 'id', type: 'uuid', nullable: false, defaultValue: 'gen_random_uuid()' },
        { name: 'company_id', type: 'uuid', nullable: false },
        { name: 'code', type: 'character varying(50)', nullable: false },
        { name: 'collection', type: 'character varying(100)', nullable: true },
        { name: 'description', type: 'text', nullable: false },
        { name: 'unit', type: 'character varying(20)', nullable: true, defaultValue: '\'sqft\'::character varying' },
        { name: 'submitted_by', type: 'uuid', nullable: false },
        { name: 'is_approved_for_global', type: 'boolean', nullable: true, defaultValue: 'false' },
        { name: 'global_product_id', type: 'uuid', nullable: true },
        { name: 'created_at', type: 'timestamp with time zone', nullable: false, defaultValue: 'now()' },
        { name: 'updated_at', type: 'timestamp with time zone', nullable: false, defaultValue: 'now()' }
      ],
      constraints: [
        { name: 'company_product_definitions_pkey', type: 'PRIMARY KEY', columns: ['id'] },
        { name: 'idx_company_products_company_code_unique', type: 'UNIQUE', columns: ['company_id', 'code'] }
      ],
      indexes: [
        { name: 'idx_company_products_company_id', columns: ['company_id'], unique: false, type: 'btree' },
        { name: 'idx_company_products_code', columns: ['code'], unique: false, type: 'btree' },
        { name: 'idx_company_products_submitted_by', columns: ['submitted_by'], unique: false, type: 'btree' },
        { name: 'idx_company_products_approval_status', columns: ['is_approved_for_global'], unique: false, type: 'btree' }
      ]
    },

    // ============================================================
    // PENDING_PRODUCTS TABLE
    // ============================================================
    {
      name: 'pending_products',
      columns: [
        { name: 'id', type: 'uuid', nullable: false, defaultValue: 'gen_random_uuid()' },
        { name: 'company_id', type: 'uuid', nullable: false },
        { name: 'code', type: 'character varying(50)', nullable: false },
        { name: 'collection', type: 'character varying(100)', nullable: true },
        { name: 'description', type: 'text', nullable: false },
        { name: 'unit', type: 'character varying(20)', nullable: true, defaultValue: '\'sqft\'::character varying' },
        { name: 'status', type: 'character varying(20)', nullable: true, defaultValue: '\'pending\'::character varying' },
        { name: 'submitted_by', type: 'uuid', nullable: true },
        { name: 'reviewed_by', type: 'uuid', nullable: true },
        { name: 'review_notes', type: 'text', nullable: true },
        { name: 'created_at', type: 'timestamp with time zone', nullable: false, defaultValue: 'now()' },
        { name: 'updated_at', type: 'timestamp with time zone', nullable: false, defaultValue: 'now()' },
        { name: 'reviewed_at', type: 'timestamp with time zone', nullable: true }
      ],
      constraints: [
        { name: 'pending_products_pkey', type: 'PRIMARY KEY', columns: ['id'] },
        { name: 'pending_products_status_check', type: 'CHECK', columns: ['status'], checkCondition: 'status IN (\'pending\', \'approved\', \'rejected\')' }
      ],
      indexes: []
    },

    // ============================================================
    // QUOTES TABLE
    // ============================================================
    {
      name: 'quotes',
      columns: [
        { name: 'id', type: 'uuid', nullable: false, defaultValue: 'gen_random_uuid()' },
        { name: 'quote_number', type: 'text', nullable: false },
        { name: 'customer_name', type: 'text', nullable: true },
        { name: 'customer_address', type: 'text', nullable: true },
        { name: 'quote_date', type: 'date', nullable: false, defaultValue: 'CURRENT_DATE' },
        { name: 'our_ref', type: 'text', nullable: true },
        { name: 'installation_fee', type: 'numeric', nullable: false, defaultValue: '0' },
        { name: 'delivery_fee', type: 'numeric', nullable: false, defaultValue: '0' },
        { name: 'subtotal', type: 'numeric', nullable: false, defaultValue: '0' },
        { name: 'total', type: 'numeric', nullable: false, defaultValue: '0' },
        { name: 'total_area', type: 'numeric', nullable: false, defaultValue: '0' },
        { name: 'panel_count', type: 'integer', nullable: false, defaultValue: '0' },
        { name: 'status', type: 'text', nullable: false, defaultValue: '\'draft\'::text' },
        { name: 'created_at', type: 'timestamp with time zone', nullable: false, defaultValue: 'now()' },
        { name: 'updated_at', type: 'timestamp with time zone', nullable: false, defaultValue: 'now()' },
        { name: 'company_id', type: 'uuid', nullable: true },
        { name: 'customer_name_encrypted', type: 'bytea', nullable: true },
        { name: 'customer_address_encrypted', type: 'bytea', nullable: true }
      ],
      constraints: [
        { name: 'quotes_pkey', type: 'PRIMARY KEY', columns: ['id'] },
        { name: 'quotes_quote_number_key', type: 'UNIQUE', columns: ['quote_number'] },
        { name: 'quotes_status_check', type: 'CHECK', columns: ['status'], checkCondition: 'status IN (\'draft\', ' + '\'pending\', \'approved\', \'rejected\', \'delivered\')' }
      ],
      indexes: [
        { name: 'quotes_quote_number_key', columns: ['quote_number'], unique: true, type: 'btree' }
      ]
    },

    // ============================================================
    // QUOTE_ITEMS TABLE
    // ============================================================
    {
      name: 'quote_items',
      columns: [
        { name: 'id', type: 'uuid', nullable: false, defaultValue: 'gen_random_uuid()' },
        { name: 'quote_id', type: 'uuid', nullable: false },
        { name: 'sort_order', type: 'integer', nullable: false, defaultValue: '0' },
        { name: 'location', type: 'text', nullable: true },
        { name: 'product_id', type: 'uuid', nullable: true },
        { name: 'product_code', type: 'text', nullable: true },
        { name: 'product_collection', type: 'text', nullable: true },
        { name: 'product_description', type: 'text', nullable: true },
        { name: 'unit', type: 'text', nullable: false, defaultValue: '\'in\'::text' },
        { name: 'is_fixed', type: 'boolean', nullable: false, defaultValue: 'true' },
        { name: 'measured_width', type: 'numeric', nullable: false, defaultValue: '0' },
        { name: 'measured_drop', type: 'numeric', nullable: false, defaultValue: '0' },
        { name: 'final_width', type: 'numeric', nullable: false, defaultValue: '0' },
        { name: 'final_drop', type: 'numeric', nullable: false, defaultValue: '0' },
        { name: 'area_sqft', type: 'numeric', nullable: false, defaultValue: '0' },
        { name: 'retail_price_sqft', type: 'numeric', nullable: false, defaultValue: '0' },
        { name: 'supplier_cost_sqft', type: 'numeric', nullable: false, defaultValue: '0' },
        { name: 'retail_amount', type: 'numeric', nullable: false, defaultValue: '0' },
        { name: 'supplier_amount', type: 'numeric', nullable: false, defaultValue: '0' },
        { name: 'created_at', type: 'timestamp with time zone', nullable: false, defaultValue: 'now()' },
        { name: 'cost_breakdown', type: 'jsonb', nullable: true, defaultValue: '\'{}\'}::jsonb' },
        { name: 'product_source', type: 'character varying(20)', nullable: true, defaultValue: '\'approved\'::character varying' },
        { name: 'pending_product_id', type: 'uuid', nullable: true }
      ],
      constraints: [
        { name: 'quote_items_pkey', type: 'PRIMARY KEY', columns: ['id'] },
        { name: 'quote_items_unit_check', type: 'CHECK', columns: ['unit'], checkCondition: 'unit IN (\'in\', \'ft\', \'cm\', \'m\')' },
        { name: 'check_product_source', type: 'CHECK', columns: ['product_source'], checkCondition: 'product_source IN (\'approved\', \'pending\', \'custom\')' }
      ],
      indexes: [
        { name: 'quote_items_quote_id_idx', columns: ['quote_id'], unique: false, type: 'btree' },
        { name: 'idx_quote_items_product_source', columns: ['product_source'], unique: false, type: 'btree' },
        { name: 'idx_quote_items_pending_product', columns: ['pending_product_id'], unique: false, type: 'btree' }
      ]
    },

    // ============================================================
    // SUBSCRIPTION_PLANS TABLE
    // ============================================================
    {
      name: 'subscription_plans',
      columns: [
        { name: 'id', type: 'uuid', nullable: false, defaultValue: 'gen_random_uuid()' },
        { name: 'name', type: 'text', nullable: false },
        { name: 'amount', type: 'numeric', nullable: false },
        { name: 'currency', type: 'text', nullable: false, defaultValue: '\'PHP\'::text' },
        { name: 'interval', type: 'text', nullable: false, defaultValue: '\'month\'::text' },
        { name: 'features', type: 'jsonb', nullable: true, defaultValue: '\'{}\'}::jsonb' },
        { name: 'created_at', type: 'timestamp with time zone', nullable: false, defaultValue: 'now()' },
        { name: 'updated_at', type: 'timestamp with time zone', nullable: false, defaultValue: 'now()' }
      ],
      constraints: [
        { name: 'subscription_plans_pkey', type: 'PRIMARY KEY', columns: ['id'] },
        { name: 'subscription_plans_name_key', type: 'UNIQUE', columns: ['name'] }
      ],
      indexes: []
    },

    // ============================================================
    // SUBSCRIPTIONS TABLE
    // ============================================================
    {
      name: 'subscriptions',
      columns: [
        { name: 'id', type: 'uuid', nullable: false, defaultValue: 'gen_random_uuid()' },
        { name: 'company_id', type: 'uuid', nullable: false },
        { name: 'status', type: 'text', nullable: false, defaultValue: '\'trialing\'::text' },
        { name: 'plan_id', type: 'uuid', nullable: false },
        { name: 'trial_end', type: 'timestamp with time zone', nullable: true },
        { name: 'current_period_end', type: 'timestamp with time zone', nullable: true },
        { name: 'cancel_at_period_end', type: 'boolean', nullable: false, defaultValue: 'false' },
        { name: 'paymongo_subscription_id', type: 'text', nullable: true },
        { name: 'created_at', type: 'timestamp with time zone', nullable: false, defaultValue: 'now()' },
        { name: 'updated_at', type: 'timestamp with time zone', nullable: false, defaultValue: 'now()' }
      ],
      constraints: [
        { name: 'subscriptions_pkey', type: 'PRIMARY KEY', columns: ['id'] },
        { name: 'subscriptions_company_id_key', type: 'UNIQUE', columns: ['company_id'] },
        { name: 'subscriptions_paymongo_subscription_id_key', type: 'UNIQUE', columns: ['paymongo_subscription_id'] },
        { name: 'subscriptions_status_check', type: 'CHECK', columns: ['status'], checkCondition: 'status IN (\'trialing\', \'active\', \'past_due\', \'cancelled\', \'unpaid\')' }
      ],
      indexes: [
        { name: 'idx_subscriptions_company_id', columns: ['company_id'], unique: false, type: 'btree' },
        { name: 'idx_subscriptions_status', columns: ['status'], unique: false, type: 'btree' },
        { name: 'idx_subscriptions_paymongo_id', columns: ['paymongo_subscription_id'], unique: false, type: 'btree' }
      ]
    },

    // ============================================================
    // SUBSCRIPTION_ITEMS TABLE
    // ============================================================
    {
      name: 'subscription_items',
      columns: [
        { name: 'id', type: 'uuid', nullable: false, defaultValue: 'gen_random_uuid()' },
        { name: 'subscription_id', type: 'uuid', nullable: false },
        { name: 'plan_id', type: 'uuid', nullable: false },
        { name: 'quantity', type: 'integer', nullable: false, defaultValue: '1' },
        { name: 'price', type: 'numeric', nullable: false },
        { name: 'created_at', type: 'timestamp with time zone', nullable: false, defaultValue: 'now()' },
        { name: 'updated_at', type: 'timestamp with time zone', nullable: false, defaultValue: 'now()' }
      ],
      constraints: [
        { name: 'subscription_items_pkey', type: 'PRIMARY KEY', columns: ['id'] }
      ],
      indexes: [
        { name: 'idx_subscription_items_subscription_id', columns: ['subscription_id'], unique: false, type: 'btree' }
      ]
    },

    // ============================================================
    // INVOICES TABLE
    // ============================================================
    {
      name: 'invoices',
      columns: [
        { name: 'id', type: 'uuid', nullable: false, defaultValue: 'gen_random_uuid()' },
        { name: 'subscription_id', type: 'uuid', nullable: false },
        { name: 'company_id', type: 'uuid', nullable: false },
        { name: 'number', type: 'text', nullable: false },
        { name: 'amount_due', type: 'numeric', nullable: false },
        { name: 'amount_paid', type: 'numeric', nullable: false, defaultValue: '0' },
        { name: 'currency', type: 'text', nullable: false, defaultValue: '\'PHP\'::text' },
        { name: 'status', type: 'text', nullable: false, defaultValue: '\'draft\'::text' },
        { name: 'paid_at', type: 'timestamp with time zone', nullable: true },
        { name: 'attempt_count', type: 'integer', nullable: false, defaultValue: '0' },
        { name: 'paymongo_invoice_id', type: 'text', nullable: true },
        { name: 'created_at', type: 'timestamp with time zone', nullable: false, defaultValue: 'now()' },
        { name: 'updated_at', type: 'timestamp with time zone', nullable: false, defaultValue: 'now()' }
      ],
      constraints: [
        { name: 'invoices_pkey', type: 'PRIMARY KEY', columns: ['id'] },
        { name: 'invoices_number_key', type: 'UNIQUE', columns: ['number'] },
        { name: 'invoices_paymongo_invoice_id_key', type: 'UNIQUE', columns: ['paymongo_invoice_id'] },
        { name: 'invoices_status_check', type: 'CHECK', columns: ['status'], checkCondition: 'status IN (\'draft\', \'open\', \'paid\', \'void\', \'uncollectible\')' }
      ],
      indexes: [
        { name: 'idx_invoices_subscription_id', columns: ['subscription_id'], unique: false, type: 'btree' },
        { name: 'idx_invoices_company_id', columns: ['company_id'], unique: false, type: 'btree' },
        { name: 'idx_invoices_status', columns: ['status'], unique: false, type: 'btree' }
      ]
    },

    // ============================================================
    // PAYMENT_METHODS TABLE
    // ============================================================
    {
      name: 'payment_methods',
      columns: [
        { name: 'id', type: 'uuid', nullable: false, defaultValue: 'gen_random_uuid()' },
        { name: 'company_id', type: 'uuid', nullable: false },
        { name: 'paymongo_payment_method_id', type: 'text', nullable: false },
        { name: 'type', type: 'text', nullable: false },
        { name: 'card_last4', type: 'text', nullable: true },
        { name: 'expiry_date', type: 'text', nullable: true },
        { name: 'is_default', type: 'boolean', nullable: false, defaultValue: 'false' },
        { name: 'created_at', type: 'timestamp with time zone', nullable: false, defaultValue: 'now()' },
        { name: 'updated_at', type: 'timestamp with time zone', nullable: false, defaultValue: 'now()' }
      ],
      constraints: [
        { name: 'payment_methods_pkey', type: 'PRIMARY KEY', columns: ['id'] },
        { name: 'payment_methods_paymongo_payment_method_id_key', type: 'UNIQUE', columns: ['paymongo_payment_method_id'] },
        { name: 'payment_methods_type_check', type: 'CHECK', columns: ['type'], checkCondition: 'type IN (\'card\', ' + '\'bank_account\', \'wallet\', \'qr_payment\')' }
      ],
      indexes: [
        { name: 'idx_payment_methods_company_id', columns: ['company_id'], unique: false, type: 'btree' }
      ]
    },

    // ============================================================
    // WEBHOOK_EVENTS TABLE
    // ============================================================
    {
      name: 'webhook_events',
      columns: [
        { name: 'id', type: 'uuid', nullable: false, defaultValue: 'gen_random_uuid()' },
        { name: 'event_type', type: 'text', nullable: false },
        { name: 'paymongo_event_id', type: 'text', nullable: false },
        { name: 'payload', type: 'jsonb', nullable: false },
        { name: 'processed', type: 'boolean', nullable: false, defaultValue: 'false' },
        { name: 'processing_error', type: 'text', nullable: true },
        { name: 'created_at', type: 'timestamp with time zone', nullable: false, defaultValue: 'now()' },
        { name: 'updated_at', type: 'timestamp with time zone', nullable: false, defaultValue: 'now()' }
      ],
      constraints: [
        { name: 'webhook_events_pkey', type: 'PRIMARY KEY', columns: ['id'] },
        { name: 'webhook_events_paymongo_event_id_key', type: 'UNIQUE', columns: ['paymongo_event_id'] }
      ],
      indexes: [
        { name: 'idx_webhook_events_event_type', columns: ['event_type'], unique: false, type: 'btree' },
        { name: 'idx_webhook_events_processed', columns: ['processed'], unique: false, type: 'btree' }
      ]
    },

    // ============================================================
    // ACTIVATION_CODES TABLE
    // ============================================================
    {
      name: 'activation_codes',
      columns: [
        { name: 'id', type: 'integer', nullable: false, defaultValue: 'nextval(\'activation_codes_id_seq\'::regclass)' },
        { name: 'code', type: 'character varying(255)', nullable: false },
        { name: 'discount_percent', type: 'numeric', nullable: false },
        { name: 'applicable_plans', type: 'jsonb', nullable: false, defaultValue: '\'["monthly", "quarterly", "annual"]\'::jsonb' },
        { name: 'payment_amount', type: 'numeric', nullable: true },
        { name: 'payment_currency', type: 'character varying(10)', nullable: true, defaultValue: '\'PHP\'::character varying' },
        { name: 'payment_amount_usd', type: 'numeric', nullable: true },
        { name: 'payment_method', type: 'character varying(50)', nullable: true },
        { name: 'exchange_rate', type: 'numeric', nullable: true },
        { name: 'payment_reference', type: 'character varying(255)', nullable: true },
        { name: 'payment_date', type: 'timestamp without time zone', nullable: true },
        { name: 'wallet_address', type: 'character varying(255)', nullable: true },
        { name: 'bank_reference', type: 'character varying(255)', nullable: true },
        { name: 'created_by', type: 'uuid', nullable: true },
        { name: 'created_at', type: 'timestamp without time zone', nullable: true, defaultValue: 'now()' },
        { name: 'expires_at', type: 'timestamp without time zone', nullable: true },
        { name: 'used_by', type: 'uuid', nullable: true },
        { name: 'used_at', type: 'timestamp without time zone', nullable: true },
        { name: 'used_ip_address', type: 'character varying(45)', nullable: true },
        { name: 'is_active', type: 'boolean', nullable: true, defaultValue: 'true' },
        { name: 'campaign_name', type: 'character varying(255)', nullable: true },
        { name: 'notes', type: 'text', nullable: true },
        { name: 'status_history', type: 'jsonb', nullable: true, defaultValue: '\'[]\'::jsonb' }
      ],
      constraints: [
        { name: 'activation_codes_pkey', type: 'PRIMARY KEY', columns: ['id'] },
        { name: 'activation_codes_code_key', type: 'UNIQUE', columns: ['code'] },
        { name: 'activation_codes_id_not_null', type: 'CHECK', columns: ['id'], checkCondition: 'id IS NOT NULL' },
        { name: 'activation_codes_code_not_null', type: 'CHECK', columns: ['code'], checkCondition: 'code IS NOT NULL' },
        { name: 'activation_codes_discount_percent_not_null', type: 'CHECK', columns: ['discount_percent'], checkCondition: 'discount_percent IS NOT NULL' },
        { name: 'activation_codes_applicable_plans_not_null', type: 'CHECK', columns: ['applicable_plans'], checkCondition: 'applicable_plans IS NOT NULL' }
      ],
      indexes: [
        { name: 'activation_codes_code_key', columns: ['code'], unique: true, type: 'btree' },
        { name: 'idx_activation_codes_code', columns: ['code'], unique: false, type: 'btree' },
        { name: 'idx_activation_codes_created_at', columns: ['created_at'], unique: false, type: 'btree' },
        { name: 'idx_activation_codes_used_by', columns: ['used_by'], unique: false, type: 'btree' },
        { name: 'idx_activation_codes_status', columns: ['is_active', 'used_by'], unique: false, type: 'btree' }
      ]
    }
  ],
  relationships: [
    // Foreign key relationships
    { fromTable: 'users', fromColumn: 'company_id', toTable: 'companies', toColumn: 'id', constraintName: 'users_company_id_fkey', onDelete: 'CASCADE', onUpdate: 'NO ACTION' },
    { fromTable: 'oauth_accounts', fromColumn: 'user_id', toTable: 'users', toColumn: 'id', constraintName: 'oauth_accounts_user_id_fkey', onDelete: 'CASCADE', onUpdate: 'NO ACTION' },
    { fromTable: 'password_reset_tokens', fromColumn: 'user_id', toTable: 'users', toColumn: 'id', constraintName: 'password_reset_tokens_user_id_fkey', onDelete: 'CASCADE', onUpdate: 'NO ACTION' },
    { fromTable: 'company_collections', fromColumn: 'company_id', toTable: 'companies', toColumn: 'id', constraintName: 'company_collections_company_id_fkey', onDelete: 'CASCADE', onUpdate: 'NO ACTION' },
    { fromTable: 'company_product_definitions', fromColumn: 'company_id', toTable: 'companies', toColumn: 'id', constraintName: 'company_product_definitions_company_id_fkey', onDelete: 'CASCADE', onUpdate: 'NO ACTION' },
    { fromTable: 'company_product_definitions', fromColumn: 'submitted_by', toTable: 'users', toColumn: 'id', constraintName: 'company_product_definitions_submitted_by_fkey', onDelete: 'CASCADE', onUpdate: 'NO ACTION' },
    { fromTable: 'company_product_definitions', fromColumn: 'global_product_id', toTable: 'products', toColumn: 'id', constraintName: 'company_product_definitions_global_product_id_fkey', onDelete: 'SET NULL', onUpdate: 'NO ACTION' },
    { fromTable: 'company_products', fromColumn: 'company_id', toTable: 'companies', toColumn: 'id', constraintName: 'company_products_company_id_fkey', onDelete: 'CASCADE', onUpdate: 'NO ACTION' },
    { fromTable: 'company_products', fromColumn: 'product_id', toTable: 'products', toColumn: 'id', constraintName: 'company_products_product_id_fkey', onDelete: 'CASCADE', onUpdate: 'NO ACTION' },
    { fromTable: 'pending_products', fromColumn: 'company_id', toTable: 'companies', toColumn: 'id', constraintName: 'pending_products_company_id_fkey', onDelete: 'CASCADE', onUpdate: 'NO ACTION' },
    { fromTable: 'pending_products', fromColumn: 'submitted_by', toTable: 'users', toColumn: 'id', constraintName: 'pending_products_submitted_by_fkey', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' },
    { fromTable: 'pending_products', fromColumn: 'reviewed_by', toTable: 'users', toColumn: 'id', constraintName: 'pending_products_reviewed_by_fkey', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' },
    { fromTable: 'quotes', fromColumn: 'company_id', toTable: 'companies', toColumn: 'id', constraintName: 'quotes_company_id_fkey', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' },
    { fromTable: 'quote_items', fromColumn: 'quote_id', toTable: 'quotes', toColumn: 'id', constraintName: 'quote_items_quote_id_fkey', onDelete: 'CASCADE', onUpdate: 'NO ACTION' },
    { fromTable: 'quote_items', fromColumn: 'product_id', toTable: 'products', toColumn: 'id', constraintName: 'quote_items_product_id_fkey', onDelete: 'SET NULL', onUpdate: 'NO ACTION' },
    { fromTable: 'subscriptions', fromColumn: 'company_id', toTable: 'companies', toColumn: 'id', constraintName: 'subscriptions_company_id_fkey', onDelete: 'CASCADE', onUpdate: 'NO ACTION' },
    { fromTable: 'subscriptions', fromColumn: 'plan_id', toTable: 'subscription_plans', toColumn: 'id', constraintName: 'subscriptions_plan_id_fkey', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' },
    { fromTable: 'subscription_items', fromColumn: 'subscription_id', toTable: 'subscriptions', toColumn: 'id', constraintName: 'subscription_items_subscription_id_fkey', onDelete: 'CASCADE', onUpdate: 'NO ACTION' },
    { fromTable: 'subscription_items', fromColumn: 'plan_id', toTable: 'subscription_plans', toColumn: 'id', constraintName: 'subscription_items_plan_id_fkey', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' },
    { fromTable: 'invoices', fromColumn: 'subscription_id', toTable: 'subscriptions', toColumn: 'id', constraintName: 'invoices_subscription_id_fkey', onDelete: 'SET NULL', onUpdate: 'NO ACTION' },
    { fromTable: 'invoices', fromColumn: 'company_id', toTable: 'companies', toColumn: 'id', constraintName: 'invoices_company_id_fkey', onDelete: 'CASCADE', onUpdate: 'NO ACTION' },
    { fromTable: 'payment_methods', fromColumn: 'company_id', toTable: 'companies', toColumn: 'id', constraintName: 'payment_methods_company_id_fkey', onDelete: 'CASCADE', onUpdate: 'NO ACTION' },
    { fromTable: 'activation_codes', fromColumn: 'created_by', toTable: 'users', toColumn: 'id', constraintName: 'activation_codes_created_by_fkey', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' },
    { fromTable: 'activation_codes', fromColumn: 'used_by', toTable: 'users', toColumn: 'id', constraintName: 'activation_codes_used_by_fkey', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }
  ]
};

/**
 * Generate SQL for creating a single table
 */
function generateCreateTableSQL(table: TableDefinition): string {
  const lines: string[] = [];

  lines.push(`CREATE TABLE ${table.name} (`);

  // Columns
  const columnDefs = table.columns.map((col): string => {
    let colDef = `  ${col.name} ${col.type}`;

    if (col.maxLength && (col.type.includes('character varying') || col.type.includes('varchar'))) {
      colDef = `  ${col.name} character varying(${col.maxLength})`;
    }

    if (!col.nullable) {
      colDef += ' NOT NULL';
    }

    if (col.defaultValue) {
      colDef += ` DEFAULT ${col.defaultValue}`;
    }

    return colDef;
  });

  lines.push(columnDefs.join(',\n'));

  // Primary key constraint
  const pkConstraint = table.constraints.find(c => c.type === 'PRIMARY KEY');
  if (pkConstraint) {
    lines.push(`  CONSTRAINT ${pkConstraint.name} PRIMARY KEY (${pkConstraint.columns.join(', ')})`);
  }

  lines.push(');\n');

  // Unique constraints
  table.constraints
    .filter(c => c.type === 'UNIQUE')
    .forEach(constraint => {
      lines.push(`ALTER TABLE ${table.name} ADD CONSTRAINT ${constraint.name} UNIQUE (${constraint.columns.join(', ')});`);
    });

  // Check constraints
  table.constraints
    .filter(c => c.type === 'CHECK')
    .forEach(constraint => {
      if (constraint.checkCondition) {
        lines.push(`ALTER TABLE ${table.name} ADD CONSTRAINT ${constraint.name} CHECK (${constraint.checkCondition});`);
      }
    });

  // Foreign key constraints
  PRODUCTION_SCHEMA.relationships
    .filter(rel => rel.fromTable === table.name)
    .forEach(rel => {
      lines.push(`ALTER TABLE ${rel.fromTable} ADD CONSTRAINT ${rel.constraintName} FOREIGN KEY (${rel.fromColumn}) REFERENCES ${rel.toTable}(${rel.toColumn}) ON DELETE ${rel.onDelete} ON UPDATE ${rel.onUpdate};`);
    });

  // Indexes
  table.indexes.forEach(index => {
    const uniqueClause = index.unique ? 'UNIQUE ' : '';
    const whereClause = index.where ? ` WHERE ${index.where}` : '';
    lines.push(`CREATE ${uniqueClause}INDEX ${index.name} ON ${table.name} USING ${index.type || 'btree'} (${index.columns.join(', ')})${whereClause};`);
  });

  return lines.join('\n') + '\n';
}

/**
 * Generate complete migration SQL
 */
function generateMigrationSQL(): string {
  const lines: string[] = [];

  lines.push('-- Production Database Schema Migration');
  lines.push('-- Generated from production database inspection on 2025-01-09');
  lines.push('-- Database: concetto on Neon.tech PostgreSQL');
  lines.push('--');
  lines.push('-- This migration recreates the exact production database structure');
  lines.push('-- including all tables, columns, constraints, indexes, and foreign keys');
  lines.push('');
  lines.push('-- Start transaction');
  lines.push('BEGIN;');
  lines.push('');

  // Create extension for UUID generation
  lines.push('-- Enable UUID generation');
  lines.push('CREATE EXTENSION IF NOT EXISTS "pgcrypto";');
  lines.push('');

  // Create tables in dependency order
  const orderedTables = [
    'companies',
    'users',
    'oauth_accounts',
    'password_reset_tokens',
    'products',
    'company_products',
    'company_collections',
    'company_product_definitions',
    'pending_products',
    'subscription_plans',
    'subscriptions',
    'subscription_items',
    'invoices',
    'payment_methods',
    'quotes',
    'quote_items',
    'webhook_events',
    'activation_codes'
  ];

  orderedTables.forEach(tableName => {
    const table = PRODUCTION_SCHEMA.tables.find(t => t.name === tableName);
    if (table) {
      lines.push(`-- Create ${tableName} table`);
      lines.push(generateCreateTableSQL(table));
      lines.push('');
    }
  });

  lines.push('-- Commit transaction');
  lines.push('COMMIT;');

  return lines.join('\n');
}

/**
 * Main migration function
 */
export async function runProductionSchemaMigration(): Promise<void> {
  try {
    const sql = neon(process.env.DATABASE_URL || '');

    console.log('Starting production schema migration...');

    // Generate migration SQL
    const migrationSQL = generateMigrationSQL();

    // Execute the migration using Neon's API
    // Neon's client executes SQL directly without needing .query()
    try {
      await sql(migrationSQL);
    } catch (error) {
      console.error('Migration execution failed:', error);
      throw error;
    }

    console.log('Production schema migration completed successfully!');
  } catch (error) {
    console.error('Migration failed:', error);
    throw error;
  }
}

// Export schema definition for inspection
export { PRODUCTION_SCHEMA };

// Run migration if executed directly
if (require.main === module) {
  runProductionSchemaMigration()
    .then(() => {
      console.log('Migration completed successfully');
      process.exit(0);
    })
    .catch((error) => {
      console.error('Migration failed:', error);
      process.exit(1);
    });
}