/**
 * Production Database Type Definitions
 *
 * This file contains TypeScript type definitions for all entities in the production database.
 * These types are based on the actual production database schema from Neon.tech PostgreSQL.
 * Generated by inspecting the production database on 2025-01-09.
 *
 * All types are properly typed with no `any` types and match the exact database structure.
 */

// ============================================================
// COMMON TYPES
// ============================================================

export type UUID = string;
export type Timestamp = Date;
export type TimestampWithTimezone = Date;
export type JsonB = Record<string, unknown>;
export type Bytea = Buffer;

// ============================================================
// ENUM TYPES (from CHECK constraints)
// ============================================================

export type SubscriptionStatus = 'demo' | 'trialing' | 'active' | 'past_due' | 'cancelled' | 'unpaid';
export type UserRole = 'user' | 'admin' | 'super_admin';
export type OAuthProvider = 'google' | 'facebook' | 'github';
export type ProductUnit = 'sqft' | 'sqm' | 'linear_ft' | 'linear_m' | 'each';
export type QuoteItemUnit = 'in' | 'ft' | 'cm' | 'm';
export type QuoteStatus = 'draft' | 'pending' | 'approved' | 'rejected' | 'delivered';
export type PendingProductStatus = 'pending' | 'approved' | 'rejected';
export type InvoiceStatus = 'draft' | 'open' | 'paid' | 'void' | 'uncollectible';
export type PaymentMethodType = 'card' | 'bank_account' | 'wallet' | 'qr_payment';
export type SubscriptionInterval = 'month' | 'quarter' | 'year';
export type ProductSource = 'approved' | 'pending' | 'custom';

// ============================================================
// TABLE ENTITY TYPES
// ============================================================

/**
 * Companies table entity
 * Multi-tenant company entities for the quotation system
 */
export interface Company {
  id: UUID;
  code: string;
  name: string;
  address: string | null;
  mobile: string | null;
  email: string | null;
  prepared_by: string | null;
  terms: string | null;
  del_note: string | null;
  closing_note: string | null;
  created_at: TimestampWithTimezone;
  updated_at: TimestampWithTimezone;
  cost_categories: string[]; // JSONB array
  currency: string;
  subscription_status: SubscriptionStatus;
  trial_end: TimestampWithTimezone | null;
}

/**
 * Users table entity
 * User accounts with company associations and authentication
 */
export interface User {
  id: UUID;
  company_id: UUID;
  email: string | null;
  password_hash: string | null;
  created_at: TimestampWithTimezone;
  name_encrypted: Bytea | null;
  email_encrypted: Bytea | null;
  email_hash: string | null;
  is_oauth_user: boolean | null;
  trial_expires_at: TimestampWithTimezone | null;
  subscription_activated: boolean | null;
  activation_code: string | null;
  discount_percent: number | null; // numeric
  subscription_plan: string | null;
  role: UserRole;
  is_admin: boolean | null;
}

/**
 * OAuth accounts table entity
 * Third-party authentication provider accounts
 */
export interface OAuthAccount {
  id: UUID;
  user_id: UUID;
  provider: OAuthProvider;
  provider_user_id: string;
  email: string | null;
  username: string | null;
  wallet_address: string | null;
  access_token: string | null;
  refresh_token: string | null;
  expires_at: TimestampWithTimezone | null;
  created_at: TimestampWithTimezone | null;
  updated_at: TimestampWithTimezone | null;
}

/**
 * Password reset tokens table entity
 * Tokens for password reset functionality
 */
export interface PasswordResetToken {
  id: UUID;
  user_id: UUID;
  token: string;
  expires_at: TimestampWithTimezone;
  used_at: TimestampWithTimezone | null;
  created_at: TimestampWithTimezone;
}

/**
 * Products table entity
 * Global product catalog available across all companies
 */
export interface Product {
  id: UUID;
  code: string;
  collection: string | null;
  description: string;
  unit: ProductUnit;
  active: boolean;
  created_at: TimestampWithTimezone;
  updated_at: TimestampWithTimezone;
}

/**
 * Company products table entity
 * Company-specific pricing for global products
 */
export interface CompanyProduct {
  id: UUID;
  company_id: UUID;
  product_id: UUID;
  supplier_cost: number; // numeric
  retail_price: number; // numeric
}

/**
 * Company collections table entity
 * Company-specific collection pricing
 */
export interface CompanyCollection {
  id: UUID;
  company_id: UUID;
  collection: string;
  supplier_cost: number; // numeric
  retail_price: number; // numeric
}

/**
 * Company product definitions table entity
 * Custom product definitions submitted by companies for global approval
 */
export interface CompanyProductDefinition {
  id: UUID;
  company_id: UUID;
  code: string; // character varying(50)
  collection: string | null; // character varying(100)
  description: string;
  unit: string | null; // character varying(20)
  submitted_by: UUID;
  is_approved_for_global: boolean | null;
  global_product_id: UUID | null;
  created_at: TimestampWithTimezone;
  updated_at: TimestampWithTimezone;
}

/**
 * Pending products table entity
 * Products pending review and approval
 */
export interface PendingProduct {
  id: UUID;
  company_id: UUID;
  code: string; // character varying(50)
  collection: string | null; // character varying(100)
  description: string;
  unit: string | null; // character varying(20)
  status: PendingProductStatus;
  submitted_by: UUID | null;
  reviewed_by: UUID | null;
  review_notes: string | null;
  created_at: TimestampWithTimezone;
  updated_at: TimestampWithTimezone;
  reviewed_at: TimestampWithTimezone | null;
}

/**
 * Quotes table entity
 * Customer quotations for window covering products
 */
export interface Quote {
  id: UUID;
  quote_number: string;
  customer_name: string | null;
  customer_address: string | null;
  quote_date: Date;
  our_ref: string | null;
  installation_fee: number; // numeric
  delivery_fee: number; // numeric
  subtotal: number; // numeric
  total: number; // numeric
  total_area: number; // numeric
  panel_count: number; // integer
  status: QuoteStatus;
  created_at: TimestampWithTimezone;
  updated_at: TimestampWithTimezone;
  company_id: UUID | null;
  customer_name_encrypted: Bytea | null;
  customer_address_encrypted: Bytea | null;
}

/**
 * Quote items table entity
 * Individual line items within a quotation
 */
export interface QuoteItem {
  id: UUID;
  quote_id: UUID;
  sort_order: number; // integer
  location: string | null;
  product_id: UUID | null;
  product_code: string | null;
  product_collection: string | null;
  product_description: string | null;
  unit: QuoteItemUnit;
  is_fixed: boolean;
  measured_width: number; // numeric
  measured_drop: number; // numeric
  final_width: number; // numeric
  final_drop: number; // numeric
  area_sqft: number; // numeric
  retail_price_sqft: number; // numeric
  supplier_cost_sqft: number; // numeric
  retail_amount: number; // numeric
  supplier_amount: number; // numeric
  created_at: TimestampWithTimezone;
  cost_breakdown: JsonB;
  product_source: ProductSource;
  pending_product_id: UUID | null;
}

/**
 * Subscription plans table entity
 * Available subscription plans with pricing
 */
export interface SubscriptionPlan {
  id: UUID;
  name: string;
  amount: number; // numeric
  currency: string;
  interval: SubscriptionInterval;
  features: JsonB;
  created_at: TimestampWithTimezone;
  updated_at: TimestampWithTimezone;
}

/**
 * Subscriptions table entity
 * Company subscription records
 */
export interface Subscription {
  id: UUID;
  company_id: UUID;
  status: SubscriptionStatus;
  plan_id: UUID;
  trial_end: TimestampWithTimezone | null;
  current_period_end: TimestampWithTimezone | null;
  cancel_at_period_end: boolean;
  paymongo_subscription_id: string | null;
  created_at: TimestampWithTimezone;
  updated_at: TimestampWithTimezone;
}

/**
 * Subscription items table entity
 * Individual items within a subscription
 */
export interface SubscriptionItem {
  id: UUID;
  subscription_id: UUID;
  plan_id: UUID;
  quantity: number; // integer
  price: number; // numeric
  created_at: TimestampWithTimezone;
  updated_at: TimestampWithTimezone;
}

/**
 * Invoices table entity
 * Payment invoices for subscriptions
 */
export interface Invoice {
  id: UUID;
  subscription_id: UUID;
  company_id: UUID;
  number: string;
  amount_due: number; // numeric
  amount_paid: number; // numeric
  currency: string;
  status: InvoiceStatus;
  paid_at: TimestampWithTimezone | null;
  attempt_count: number; // integer
  paymongo_invoice_id: string | null;
  created_at: TimestampWithTimezone;
  updated_at: TimestampWithTimezone;
}

/**
 * Payment methods table entity
 * Payment methods stored for companies
 */
export interface PaymentMethod {
  id: UUID;
  company_id: UUID;
  paymongo_payment_method_id: string;
  type: PaymentMethodType;
  card_last4: string | null;
  expiry_date: string | null;
  is_default: boolean;
  created_at: TimestampWithTimezone;
  updated_at: TimestampWithTimezone;
}

/**
 * Webhook events table entity
 * Payment webhook events from payment processors
 */
export interface WebhookEvent {
  id: UUID;
  event_type: string;
  paymongo_event_id: string;
  payload: JsonB;
  processed: boolean;
  processing_error: string | null;
  created_at: TimestampWithTimezone;
  updated_at: TimestampWithTimezone;
}

/**
 * Activation codes table entity
 * Promotional activation codes for subscription discounts
 */
export interface ActivationCode {
  id: number; // integer with auto-increment
  code: string; // character varying(255)
  discount_percent: number; // numeric
  applicable_plans: string[]; // JSONB array
  payment_amount: number | null; // numeric
  payment_currency: string | null; // character varying(10)
  payment_amount_usd: number | null; // numeric
  payment_method: string | null; // character varying(50)
  exchange_rate: number | null; // numeric
  payment_reference: string | null; // character varying(255)
  payment_date: Date | null; // timestamp without time zone
  wallet_address: string | null; // character varying(255)
  bank_reference: string | null; // character varying(255)
  created_by: UUID | null;
  created_at: Date | null; // timestamp without time zone
  expires_at: Date | null; // timestamp without time zone
  used_by: UUID | null;
  used_at: Date | null; // timestamp without time zone
  used_ip_address: string | null; // character varying(45)
  is_active: boolean | null;
  campaign_name: string | null; // character varying(255)
  notes: string | null;
  status_history: JsonB; // JSONB array
}

// ============================================================
// RELATIONSHIP TYPES (JOIN TYPES)
// ============================================================

/**
 * Company with users relationship
 */
export interface CompanyWithUsers extends Company {
  users?: User[];
}

/**
 * User with company relationship
 */
export interface UserWithCompany extends User {
  company?: Company;
}

/**
 * Quote with items relationship
 */
export interface QuoteWithItems extends Quote {
  items?: QuoteItem[];
}

/**
 * Quote with company relationship
 */
export interface QuoteWithCompany extends Quote {
  company?: Company;
}

/**
 * Subscription with items relationship
 */
export interface SubscriptionWithItems extends Subscription {
  items?: SubscriptionItem[];
  plan?: SubscriptionPlan;
}

/**
 * Company with subscription relationship
 */
export interface CompanyWithSubscription extends Company {
  subscription?: Subscription;
}

/**
 * Product with company pricing relationship
 */
export interface ProductWithPricing extends Product {
  company_pricing?: CompanyProduct[];
}

/**
 * User with OAuth accounts relationship
 */
export interface UserWithOAuth extends User {
  oauth_accounts?: OAuthAccount[];
}

// ============================================================
// INPUT TYPES FOR CREATE/UPDATE OPERATIONS
// ============================================================

/**
 * Input type for creating a new company
 */
export interface CompanyCreateInput {
  code: string;
  name: string;
  address?: string;
  mobile?: string;
  email?: string;
  prepared_by?: string;
  terms?: string;
  del_note?: string;
  closing_note?: string;
  cost_categories?: string[];
  currency?: string;
  subscription_status?: SubscriptionStatus;
  trial_end?: Date;
}

/**
 * Input type for updating an existing company
 */
export interface CompanyUpdateInput {
  name?: string;
  address?: string;
  mobile?: string;
  email?: string;
  prepared_by?: string;
  terms?: string;
  del_note?: string;
  closing_note?: string;
  cost_categories?: string[];
  currency?: string;
  subscription_status?: SubscriptionStatus;
  trial_end?: Date;
}

/**
 * Input type for creating a new user
 */
export interface UserCreateInput {
  company_id: UUID;
  email?: string;
  password_hash?: string;
  name_encrypted?: Buffer;
  email_encrypted?: Buffer;
  email_hash?: string;
  is_oauth_user?: boolean;
  trial_expires_at?: Date;
  subscription_activated?: boolean;
  activation_code?: string;
  discount_percent?: number;
  subscription_plan?: string;
  role?: UserRole;
  is_admin?: boolean;
}

/**
 * Input type for updating an existing user
 */
export interface UserUpdateInput {
  email?: string;
  password_hash?: string;
  name_encrypted?: Buffer;
  email_encrypted?: Buffer;
  email_hash?: string;
  is_oauth_user?: boolean;
  trial_expires_at?: Date;
  subscription_activated?: boolean;
  activation_code?: string;
  discount_percent?: number;
  subscription_plan?: string;
  role?: UserRole;
  is_admin?: boolean;
}

/**
 * Input type for creating a new quote
 */
export interface QuoteCreateInput {
  quote_number: string;
  customer_name?: string;
  customer_address?: string;
  quote_date?: Date;
  our_ref?: string;
  installation_fee?: number;
  delivery_fee?: number;
  subtotal?: number;
  total?: number;
  total_area?: number;
  panel_count?: number;
  status?: QuoteStatus;
  company_id?: UUID;
  customer_name_encrypted?: Buffer;
  customer_address_encrypted?: Buffer;
}

/**
 * Input type for creating a new quote item
 */
export interface QuoteItemCreateInput {
  quote_id: UUID;
  sort_order?: number;
  location?: string;
  product_id?: UUID;
  product_code?: string;
  product_collection?: string;
  product_description?: string;
  unit?: QuoteItemUnit;
  is_fixed?: boolean;
  measured_width?: number;
  measured_drop?: number;
  final_width?: number;
  final_drop?: number;
  area_sqft?: number;
  retail_price_sqft?: number;
  supplier_cost_sqft?: number;
  retail_amount?: number;
  supplier_amount?: number;
  cost_breakdown?: JsonB;
  product_source?: ProductSource;
  pending_product_id?: UUID;
}

/**
 * Input type for creating a new subscription
 */
export interface SubscriptionCreateInput {
  company_id: UUID;
  plan_id: UUID;
  status?: SubscriptionStatus;
  trial_end?: Date;
  current_period_end?: Date;
  cancel_at_period_end?: boolean;
  paymongo_subscription_id?: string;
}

// ============================================================
// QUERY RESULT TYPES
// ============================================================

/**
 * Paginated result type
 */
export interface PaginatedResult<T> {
  data: T[];
  total: number;
  page: number;
  limit: number;
  has_more: boolean;
}

/**
 * Database query options
 */
export interface QueryOptions {
  limit?: number;
  offset?: number;
  orderBy?: string;
  orderDirection?: 'ASC' | 'DESC';
}

// ============================================================
// UTILITY TYPES FOR DATABASE OPERATIONS
// ============================================================

/**
 * Extract table name from entity type
 */
export type TableName<T> = T extends Company ? 'companies' :
  T extends User ? 'users' :
  T extends OAuthAccount ? 'oauth_accounts' :
  T extends PasswordResetToken ? 'password_reset_tokens' :
  T extends Product ? 'products' :
  T extends CompanyProduct ? 'company_products' :
  T extends CompanyCollection ? 'company_collections' :
  T extends CompanyProductDefinition ? 'company_product_definitions' :
  T extends PendingProduct ? 'pending_products' :
  T extends Quote ? 'quotes' :
  T extends QuoteItem ? 'quote_items' :
  T extends SubscriptionPlan ? 'subscription_plans' :
  T extends Subscription ? 'subscriptions' :
  T extends SubscriptionItem ? 'subscription_items' :
  T extends Invoice ? 'invoices' :
  T extends PaymentMethod ? 'payment_methods' :
  T extends WebhookEvent ? 'webhook_events' :
  T extends ActivationCode ? 'activation_codes' :
  never;

/**
 * Database entity type union
 */
export type DatabaseEntity =
  | Company
  | User
  | OAuthAccount
  | PasswordResetToken
  | Product
  | CompanyProduct
  | CompanyCollection
  | CompanyProductDefinition
  | PendingProduct
  | Quote
  | QuoteItem
  | SubscriptionPlan
  | Subscription
  | SubscriptionItem
  | Invoice
  | PaymentMethod
  | WebhookEvent
  | ActivationCode;